name: docker-staging

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: define branch name
        run: echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: define commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lus
          password: ${{ secrets.CR_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/x0tf/server:staging
          build-args:
            X0_VERSION=${{ env.BRANCH }}-${{ env.COMMIT_HASH }}