name: docker

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: define staging tag
        if: endsWith(github.ref, '/develop')
        run: echo "TAG=nightly" >> $GITHUB_ENV
      - name: define latest tag
        if: endsWith(github.ref, '/main')
        run: echo "TAG=latest" >> $GITHUB_ENV
      - name: define commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lus
          password: ${{ secrets.TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/x0tf/server:${{ env.TAG }}
            ghcr.io/x0tf/server:${{ env.COMMIT_HASH }}